[build]
command = "composer install && npm install && npm run build"

[deploy]
predeploy = """
cp .env.example .env && \
php artisan key:generate && \
php artisan migrate --force && \
"""

postdeploy = """
php artisan config:cache && \
php artisan route:cache && \
php artisan view:cache
"""

[start]
command = """php artisan serve --host=0.0.0.0 --port=8080"""
